select TMP.* 
  from TMP_ANALISE_BENEFICIARIO TMP 
  WHERE TITULAR = 'N'
    AND NOT EXISTS
        (SELECT 1
           FROM TMP_ANALISE_BENEFICIARIO TMP2
          WHERE TMP2.CPF = TMP.CPFTITULAR
            AND TMP2.FAMILIA = TMP.FAMILIA
            AND TMP2.CONTRATO = TMP.CONTRATO
            AND TMP2.ARQUIVO = TMP.ARQUIVO
            AND TMP2.TITULAR = 'S'
            AND TO_NUMBER(TMP2.SEQUENCIAL_LINHA) < TO_NUMBER(TMP.SEQUENCIAL_LINHA))           
  ORDER BY ARQUIVO,TO_NUMBER(SEQUENCIAL_LINHA)
  
  
SELECT * FROM TMP_ANALISE_BENEFICIARIO WHERE ARQUIVO = '20251105_1_beneficiario_emp_7.txt' AND SEQUENCIAL_LINHA IN ('1682','1688')
  
           
