select NOME, TO_NUMBER(TMP.CONTRATO) EMPRESA,MATRICULAFUNCIONAL, SUBSTR(FAMILIA, LENGTH(FAMILIA),1) GRUPOFAMILIAR, TO_NUMBER(DEPENDENTE) CODIGODEPENDENTE, CPF, CPFTITULAR,LPAD(TO_NUMBER(CONTRATO),2,0)||LPAD(MATRICULAFUNCIONAL,8,0)||LPAD(TO_NUMBER(DEPENDENTE),2,0)CARTEIRINHA 
  from TMP_ANALISE_BENEFICIARIO TMP 
  WHERE TITULAR = 'N'
    AND TMP.DATACANCELAMENTO IS NULL
    AND  NOT EXISTS
        (SELECT 1
           FROM TMP_ANALISE_BENEFICIARIO TMP2
          WHERE TMP2.FAMILIA = TMP.FAMILIA
            AND TMP2.CONTRATO = TMP.CONTRATO
            AND TMP2.ARQUIVO = TMP.ARQUIVO
            AND TMP2.TITULAR = 'S'
            AND TMP2.DATACANCELAMENTO IS  NULL
          )                       
MINUS     
select NOME, TO_NUMBER(TMP.CONTRATO) EMPRESA,MATRICULAFUNCIONAL, SUBSTR(FAMILIA, LENGTH(FAMILIA),1) GRUPOFAMILIAR, TO_NUMBER(DEPENDENTE) CODIGODEPENDENTE, CPF, CPFTITULAR,LPAD(TO_NUMBER(CONTRATO),2,0)||LPAD(MATRICULAFUNCIONAL,8,0)||LPAD(TO_NUMBER(DEPENDENTE),2,0)CARTEIRINHA 
  from TMP_ANALISE_BENEFICIARIO TMP 
  WHERE TITULAR = 'N'
    AND TMP.DATACANCELAMENTO IS NULL
    AND  NOT EXISTS
        (SELECT 1
           FROM TMP_ANALISE_BENEFICIARIO TMP2
          WHERE TMP2.MATRICULAFUNCIONAL = TMP.MATRICULAFUNCIONAL
            AND TMP2.CONTRATO = TMP.CONTRATO
            AND TMP2.ARQUIVO = TMP.ARQUIVO
            AND TMP2.TITULAR = 'S'
            AND TMP2.DATACANCELAMENTO IS  NULL
          )    
  ORDER BY ARQUIVO,TO_NUMBER(SEQUENCIAL_LINHA)
  
  
  SELECT * FROM TMP_ANALISE_BENEFICIARIO WHERE CPF = '07600140780'
  
  
SELECT * FROM TMP_ANALISE_BENEFICIARIO WHERE ARQUIVO = '20251105_1_beneficiario_emp_7.txt' AND SEQUENCIAL_LINHA IN ('1682','1688')
  
           
