select TMP.* 
  from TMP_ANALISE_BENEFICIARIO TMP 
  WHERE TITULAR = 'N'
    AND TMP.DATACANCELAMENTO IS NULL
    AND  NOT EXISTS
        (SELECT 1
           FROM TMP_ANALISE_BENEFICIARIO TMP2
          WHERE TMP2.FAMILIA = TMP.FAMILIA
            AND TMP2.CONTRATO = TMP.CONTRATO
            AND TMP2.ARQUIVO = TMP.ARQUIVO
            AND TMP2.TITULAR = 'S'
            AND TMP2.DATACANCELAMENTO IS  NULL
          )           
  ORDER BY ARQUIVO,TO_NUMBER(SEQUENCIAL_LINHA)
  
  
SELECT * FROM TMP_ANALISE_BENEFICIARIO WHERE ARQUIVO = '20251105_1_beneficiario_emp_7.txt' AND SEQUENCIAL_LINHA IN ('1682','1688')
  
           
