select TMP.NOME, TO_NUMBER(CONTRATO) EMPRESA, MATRICULAFUNCIONAL, TO_NUMBER(DEPENDENTE) CODIGODEPENDENTE, SUBSTR(FAMILIA,LENGTH(FAMILIA),1) GRUPOFAMILIAR, 
LPAD(TO_NUMBER(CONTRATO),2,0)||LPAD(MATRICULAFUNCIONAL,8,0)||LPAD(TO_NUMBER(DEPENDENTE),2,0)CARTEIRINHA
  from TMP_ANALISE_BENEFICIARIO TMP
 where EXISTS 
       (SELECT 1
          FROM TMP_ANALISE_BENEFICIARIO TMP2
          WHERE TMP2.SEQUENCIAL_LINHA <> TMP.SEQUENCIAL_LINHA
            AND TMP2.CONTRATO = TMP.CONTRATO
            AND TMP2.FAMILIA = TMP.FAMILIA
            AND TMP2.TITULAR = TMP.TITULAR)
  AND TMP.TITULAR = 'S'   
  AND TMP.DATACANCELAMENTO IS NULL       
ORDER BY CONTRATO, FAMILIA            
