SELECT * FROM
(SELECT NOME, TO_NUMBER(TMP.CONTRATO) EMPRESA,MATRICULAFUNCIONAL, TO_NUMBER(DEPENDENTE) CODIGODEPENDENTE,SUBSTR(FAMILIA, LENGTH(FAMILIA),1) GRUPOFAMILIAR,LPAD(TO_NUMBER(CONTRATO),2,0)||LPAD(MATRICULAFUNCIONAL,8,0)||LPAD(TO_NUMBER(DEPENDENTE),2,0)CARTEIRINHA 
  from TMP_ANALISE_BENEFICIARIO TMP 
  WHERE  EXISTS
        (SELECT 1
           FROM TMP_ANALISE_BENEFICIARIO TMP2
          WHERE TMP2.FAMILIA = TMP.FAMILIA
            AND TMP2.CONTRATO = TMP.CONTRATO
            AND TMP2.DATACANCELAMENTO IS NULL
            AND TMP2.ARQUIVO <> TMP.ARQUIVO)
union
SELECT NOME, TO_NUMBER(TMP.CONTRATO) EMPRESA,MATRICULAFUNCIONAL, TO_NUMBER(DEPENDENTE) CODIGODEPENDENTE,SUBSTR(FAMILIA, LENGTH(FAMILIA),1) GRUPOFAMILIAR,LPAD(TO_NUMBER(CONTRATO),2,0)||LPAD(MATRICULAFUNCIONAL,8,0)||LPAD(TO_NUMBER(DEPENDENTE),2,0)CARTEIRINHA 
  from TMP_ANALISE_BENEFICIARIO TMP 
  WHERE  EXISTS
        (SELECT 1
           FROM TMP_ANALISE_BENEFICIARIO TMP2
          WHERE TMP2.MATRICULAFUNCIONAL = TMP.MATRICULAFUNCIONAL
            AND TMP2.CONTRATO = TMP.CONTRATO
            AND TMP2.DATACANCELAMENTO IS NULL
            AND TMP2.ARQUIVO <> TMP.ARQUIVO)) X
   ORDER BY X.EMPRESA, X.MATRICULAFUNCIONAL          
  
  
SELECT * FROM TMP_ANALISE_BENEFICIARIO WHERE ARQUIVO = '20251105_1_beneficiario_emp_7.txt' AND SEQUENCIAL_LINHA IN ('1682','1688')
  
           
